---
- name: import Nodesource RPM key
  rpm_key: key=https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL state=present

- name: install NodeSource repository
  yum: name={{ node_nodesource_download_url }} state=present

- name: install nodejs
  yum: name=nodejs-{{ node_version }} state=present

- name: update npm
  command: /bin/npm update -g npm
  when: node_update_npm_enabled == True
